### ISSUE TITLE
[Bug Report] 피드백 제출이 안돼요

### ISSUE THREAD

**Issue by sen2y** [100-hours-a-week/5-chunsik-4Q-fe#5]
## 🐛 버그 설명

- 🐛 버그 
피드백 제출버튼 눌러도 안됩니다. 유효성검사 헬퍼텍스트가 뜨거나 다른 알림이 뜨지않아 해당 서비스가 되는 기능인데 안되는건지 파악이 안됩니다.

## 🔄 재현하는 방법
동작을 재현하는 단계:
1. 메뉴에서 피드백 주기 클릭 
2. 별점이랑 어느것이 쉬웠나요?만 선택한 뒤, 제출하기 버튼 클릭 

## ✅ 예상한 동작

- ✅ 예상동작 
제출완료가 뜨고 메인 화면으로 돌아갈 줄 알았다.
## 📸 스크린샷 (옵션)
[문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.]
(https://www.qqqq.world/4q-create)

## 🖥️ 데스크톱(다음 정보를 작성해 주세요):
 - OS: MacOS
 - Browser  chrome  

 
## ℹ️ 추가적인 내용 (옵션):
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by moolmin** [comment]
피드백 제출이 정상적으로 되도록 fecth 수정 완 🙇‍♀️
