### ISSUE TITLE
[Bug Report] 로그인이 되어 있는 상태에서 로그아웃 후에 로그인을 다시하면 햄버거바 메뉴에 로그인 버튼이 뜨고 로그아웃이 안떠요.

### ISSUE THREAD

**Issue by TopazKang** [100-hours-a-week/5-chunsik-4Q-fe#6]
## 🐛 버그 설명
버그에 대한 명확하고 간결한 설명해주세요.
- 🐛 로그인이 되어 있는 상태에서 로그아웃 후에 곧바로 로그인하면 메인화면으로 연결되는데, 해당 화면에서 다시 메뉴를 띄우면 로그인 상태 반영이 되지 않아 로그아웃이 아닌 로그인 버튼이 표시됨.

## 🔄 재현하는 방법
동작을 재현하는 단계:
1. 로그인
2. 메뉴를 눌러 로그아웃
3. 로그아웃이 되어 카카오 로그인 화면이 나오게 되면 곧바로 다시 로그인
4. 로그인이 되고 메인화면으로 이동되면 메뉴바 클릭
5. 버그발생: 메뉴를 확인하면 로그아웃 버튼이 아닌 로그인 버튼이 아직도 보이는 상태를 확인 가능

## ✅ 예상한 동작
예상했던 일에 대한 명확하고 간결한 설명해주세요.
- ✅ 로그인이 되어 있는 상태이기 때문에 로그아웃 버튼이 나올것으로 예상함.

## 📸 스크린샷 (옵션)
문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.

https://github.com/user-attachments/assets/ec49f3e2-bc6d-492b-8a88-318672a616ef

## 🖥️ 데스크톱(다음 정보를 작성해 주세요):
 - OS: [Mac os]
 - Browser [chrome]
 - Version []

## 📱 스마트폰(다음 정보를 입력하세요):
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

## ℹ️ 추가적인 내용 (옵션):
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by moolmin** [comment]
context api를 활용해 이슈 해결했습니다
