### ISSUE TITLE
[Bug Report] 로그아웃하고 다시 로그인하면 로그인이 안돼요

### ISSUE THREAD

**Issue by sen2y** [100-hours-a-week/5-chunsik-4Q-fe#7]
## 🐛 버그 설명

- 🐛 버그 
로그아웃 한 뒤에 다시 로그인을 하고 메뉴를 클릭하면 로그인이 뜹니다. -> 기대한 상황 : 로그아웃이 노출되어야함
이상황에서 로그인 한번 더하면 그때 로그아웃이 노출됩니다

## 🔄 재현하는 방법
동작을 재현하는 단계:
1. 로그인한다
2. 로그아웃한다
3. 로그인한다

## ✅ 예상한 동작

- ✅ 예상동작 
3번 이후 메뉴탭에 로그아웃이 떠야하는데, 여전히 로그인 버튼으로 출력
## 📸 스크린샷 (옵션)
문제를 설명하는 데 도움이 되는 스크린샷을 추가하세요. 스크린샷으로 어렵다면 영상첨부해주세요.
https://www.awesomescreenshot.com/video/30920548?key=88027aeb80708a7cefda3f8bdc44cae4
## 🖥️ 데스크톱(다음 정보를 작성해 주세요):
 - OS: [예) iOS]
 - Browser [예) chrome, safari]
 - Version [예) 22]

## 📱 스마트폰(다음 정보를 입력하세요):
 - Device: [예) iPhone6]
 - OS: [예) iOS8.1]
 - Browser [예) chrome, safari]
 - Version [예) 22]

## ℹ️ 추가적인 내용 (옵션):
여기에 문제에 대한 다른 컨텍스트를 추가해주세요.

**Comment by moolmin** [comment]
context api를 활용해 이슈 해결했습니다
